### ISSUE TITLE
BOM wrong part for R43?

### ISSUE THREAD

**Issue by beliefsystemrecords** [MagpieModular/Plancks#1]
In the bom the part no for the 49,9k resistor is for a 33k resistor. maybe update the bom?

**Comment by MagpieModular** [comment]
Thanks for filing the issue! I've gone ahead and fixed the BOM to reflect the correct part mouser part number for R43 (49.9k)

Fixed in 5489765bbd4b6c9e94e079e701c2d3c45922c5bf
